CREATE DATABASE IF NOT EXISTS ce_stream_spike;
CREATE TABLE IF NOT EXISTS ce_stream_spike.t1 (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE USER IF NOT EXISTS 'ce_stream'@'%' IDENTIFIED BY 'CeStreamSpike9!';
GRANT REPLICATION SLAVE, REPLICATION CLIENT, SELECT ON *.* TO 'ce_stream'@'%';
GRANT ALL ON ce_stream_spike.* TO 'ce_stream'@'%';
FLUSH PRIVILEGES;
SELECT user, host FROM mysql.user WHERE user='ce_stream';
